ssrsp=[
    {
        "name": "兵蠺玉带·烟",
        "icon": "Equip_bingjingyudai",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+10%，气血+5%",
        "job": "111111",
        "type": "100001",
        "lv": 0
    },
    {
        "name": "兵蠺玉带·尘",
        "icon": "Equip_bingjingyudai",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+10%，物防+5%",
        "job": "111111",
        "type": "110000",
        "lv": 0
    },
    {
        "name": "兵蠺玉带·雾",
        "icon": "Equip_bingjingyudai",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+5%，气血+5%。主动攻击「对战后」，对敌人造成一次「固定伤害」（物攻的15%）",
        "job": "111111",
        "type": "100001",
        "lv": 0
    },
    {
        "name": "绮罗天香·烟",
        "icon": "Equip_qiluotianxiang",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+8%，主动攻击「对战后」，50%概率对目标施加「蚀御」效果，持续1回合。\n「蚀御」：物防-20%",
        "job": "111111",
        "type": "100000",
        "lv": 0
    },
    {
        "name": "绮罗天香·尘",
        "icon": "Equip_qiluotianxiang",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+8%，主动攻击「对战后」，50%概率对目标施加「疲弱」效果，持续1回合。\n「疲弱」：物攻，法攻-20%",
        "job": "111111",
        "type": "100000",
        "lv": 0
    },
    {
        "name": "绮罗天香·雾",
        "icon": "Equip_qiluotianxiang",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+8%，主动攻击「对战后」，50%概率驱散敌人1个「有益状态」",
        "job": "111111",
        "type": "100000",
        "lv": 0
    },
    {
        "name": "神乌饰坠·烟",
        "icon": "Equip_shenwushizhui",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+10%，气血+5%",
        "job": "111111",
        "type": "001001",
        "lv": 0
    },
    {
        "name": "神乌饰坠·尘",
        "icon": "Equip_shenwushizhui",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+10%，法防+5%",
        "job": "111111",
        "type": "001100",
        "lv": 0
    },
    {
        "name": "火纹硅玉",
        "icon": "Equip_huowenguiyu",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+5%，主动攻击「对战后」，50%概率对目标施加「燃烧」状态，持续2回合。\n「燃烧」：行动结束时，损失12%气血（上限2层）",
        "job": "111111",
        "type": "001000",
        "lv": 0
    },
    {
        "name": "冷华幽镜",
        "icon": "Equip_lenghuayoujing",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+8%，主动攻击「对战后」，50%概率施加「蚀魔」效果，持续1回合。\n「蚀魔」：法防-30%",
        "job": "111111",
        "type": "001000",
        "lv": 0
    },
    {
        "name": "六芒星印·烟",
        "icon": "Equip_liumangxingyin",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+5%，法防+5%，主动造成伤害后，30%概率施加「污秽」效果，持续1回合。\n「污秽」：无法获得任何「有益状态」",
        "job": "111111",
        "type": "001100",
        "lv": 0
    },
    {
        "name": "六芒星印·尘",
        "icon": "Equip_liumangxingyin",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+5%，物防+5%，主动造成伤害后，30%概率施加「禁疗」效果，持续1回合。\n「禁疗」无法被治疗",
        "job": "111111",
        "type": "011000",
        "lv": 0
    },
    {
        "name": "六芒星印·雾",
        "icon": "Equip_liumangxingyin",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+5%，气血+5%，主动造成伤害后，30%概率施加「迟缓I」效果，持续1回合。\n「迟缓I」移动力-1，无法护卫",
        "job": "111111",
        "type": "001001",
        "lv": 0
    },
    {
        "name": "龙骨项链·烟",
        "icon": "Equip_longgusuipian",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+15%，对友方使用单体绝学时，附加「御魔」效果，持续1回合。\n「御魔」：法防+30%",
        "job": "111111",
        "type": "000010",
        "lv": 0
    },
    {
        "name": "龙骨项链·尘",
        "icon": "Equip_longgusuipian",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+15%，对友方使用单体绝学时，附加「披甲」效果，持续1回合。\n「披甲」：物防+20%",
        "job": "111111",
        "type": "000010",
        "lv": 0
    },
    {
        "name": "天狼血眼",
        "icon": "Equip_tianlangxueyan",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，主动攻击「对战前」，每移动1格，物攻、物防提升5%（最高15%）",
        "job": "111111",
        "type": "000001",
        "lv": 1
    },
    {
        "name": "冰蟾串珠·烟",
        "icon": "Equip_bingchanchuanzhu",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+10%，主动攻击「对战前」施加「封脉」效果，持续1回合。「封脉」：所有被动「绝学」失效",
        "job": "101000",
        "type": "100000",
        "lv": 1
    },
    {
        "name": "冰蟾串珠·尘",
        "icon": "Equip_bingchanchuanzhu",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+10%，主动攻击「对战前」施加「封穴」效果，持续1回合。「封穴」：无法发动「连击」「追击」和「闪避」",
        "job": "010001",
        "type": "100000",
        "lv": 1
    },
    {
        "name": "如意珠翠",
        "icon": "Equip_ruyizhucui",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+5%，暴击率+5%。造成暴击「战斗后」，对目标造成一次「固定伤害」（物攻的20%）",
        "job": "111111",
        "type": "100000",
        "lv": 1
    },
    {
        "name": "玄乌玉雕·烟",
        "icon": "Equip_xuanwuyudiao",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+5%，气血+5%，被攻击「对战中」造成伤害提升30%。",
        "job": "111111",
        "type": "100001",
        "lv": 1
    },
    {
        "name": "玄乌玉雕·尘",
        "icon": "Equip_xuanwuyudiao",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+7%，气血+7%。主动攻击「对战前」，驱散目标身上1个「有益状态」",
        "job": "111111",
        "type": "100001",
        "lv": 1
    },
    {
        "name": "魂刹玉",
        "icon": "Equip_hunshayu",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+5%，气血+5%，与携带「有害状态」的敌人「对战中」，所有攻防属性+10%",
        "job": "111111",
        "type": "001001",
        "lv": 1
    },
    {
        "name": "太初华晶·烟",
        "icon": "Equip_taichuhuajing",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+8%，主动攻击「对战后」，施加「虚损II」和「失智II」状态，持续1回合。\n「虚损II」：物理免伤-20%\n「失智II」：法术免伤-20%",
        "job": "111111",
        "type": "001000",
        "lv": 1
    },
    {
        "name": "太初华晶·尘",
        "icon": "Equip_taichuhuajing",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+8%，主动攻击「对战后」，施加「乱神II」效果，持续1回合。\n「乱神II」：伤害-20%",
        "job": "111111",
        "type": "001000",
        "lv": 1
    },
    {
        "name": "天河朱砂",
        "icon": "Equip_tianhezhusha",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+10%，使用单体绝学时，伤害额外提升15%。",
        "job": "111111",
        "type": "001000",
        "lv": 1
    },
    {
        "name": "冰凛银环·烟",
        "icon": "Equip_binglinyinzhuo",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+10%，如果本回合使用过治疗绝学，行动结束时为气血最低的1个友方恢复气血（恢复量为施术者法攻的0.5倍）。",
        "job": "111111",
        "type": "000010",
        "lv": 1
    },
    {
        "name": "冰凛银环·尘",
        "icon": "Equip_binglinyinzhuo",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+15%，对友方使用绝学时，40%概率附加「神护II」和「固元II」状态，持续1回合。\n「神护II」：物理免伤+20%\n「固元II」：法术免伤+20%",
        "job": "111111",
        "type": "000010",
        "lv": 1
    },
    {
        "name": "七色缨珞",
        "icon": "Equip_qiseyingluo",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+8%，主动造成伤害后，追加一次「固定伤害」（物攻的10%）",
        "job": "101000",
        "type": "100000",
        "lv": 2
    },
    {
        "name": "飞凤坠饰",
        "icon": "Equip_feifengzhuishi",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "普通攻击时射程+1，同时伤害-10%",
        "job": "010000",
        "type": "100000",
        "lv": 2
    },
    {
        "name": "西方神徽",
        "icon": "Equip_xifangshenhui",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+8%。主动攻击「战斗前」，对敌人造成一次「固定伤害」（物攻的15%）",
        "job": "000001",
        "type": "100000",
        "lv": 2
    },
    {
        "name": "封豨牙悬",
        "icon": "Equip_fengxiyaxuan",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+10%，使用群体绝学时，伤害额外提升15%",
        "job": "111111",
        "type": "001000",
        "lv": 2
    },
    {
        "name": "翡翠骷髅",
        "icon": "Equip_feicuikulou",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+5%，气血+5%，主动造成伤害时，40%概率施加1个「有害状态」。",
        "job": "000100",
        "type": "001001",
        "lv": 2
    },
    {
        "name": "辰星珑坠",
        "icon": "Equip_chenxinglongzhui",
        "position": "1",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+15%，对友方使用绝学时，40%概率驱散1个「有害状态」。",
        "job": "000010",
        "type": "000010",
        "lv": 2
    },
    {
        "name": "护命神符·烟",
        "icon": "Equip_humingshenfu",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防+10%，气血+5%",
        "job": "111111",
        "type": "010001",
        "lv": 0
    },
    {
        "name": "护命神符·尘",
        "icon": "Equip_humingshenfu",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防+10%，法防+5%",
        "job": "111111",
        "type": "010100",
        "lv": 0
    },
    {
        "name": "辟邪玉佩·烟",
        "icon": "Equip_pixieyupei",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，气血高于50%时，物防+15%",
        "job": "111111",
        "type": "010001",
        "lv": 0
    },
    {
        "name": "辟邪玉佩·尘",
        "icon": "Equip_pixieyupei",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防+5%，气血低于50%时，物防+20%",
        "job": "111111",
        "type": "010000",
        "lv": 0
    },
    {
        "name": "清神净玉",
        "icon": "Equip_qingshenjingyu",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，主动攻击「对战中」物防，法防提升15%",
        "job": "111111",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "灵越佩环·烟",
        "icon": "Equip_lingyuepeihuan",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，行动结束时，对自己直线7格内的一个敌人施加「疲弱」状态，持续1回合。\n「疲弱」物攻、法攻-20%",
        "job": "101001",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "灵越佩环·尘",
        "icon": "Equip_lingyuepeihuan",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，行动结束时，对自己直线7格内的一个敌人施加「蚀御」状态，持续1回合。\n「蚀御」物防-20%",
        "job": "101001",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "灵越佩环·雾",
        "icon": "Equip_lingyuepeihuan",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，行动结束时，对自己直线7格内的一个敌人施加「蚀魔」状态，持续1回合。\n「蚀魔」法防-30%",
        "job": "101001",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "九龙玉佩",
        "icon": "Equip_jiulongyupei",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防+10%，遭受近战攻击「对战后」，对敌方施加「疲弱」状态，持续1回合。\n「疲弱」物攻、法攻-20%",
        "job": "111111",
        "type": "010000",
        "lv": 1
    },
    {
        "name": "化渊曲玉",
        "icon": "Equip_huayuanquyu",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防、气血+5%，遭受近战攻击「对战前」，对敌方造成一次「固定伤害」（物防的30%）",
        "job": "111111",
        "type": "010001",
        "lv": 1
    },
    {
        "name": "流光镜玉",
        "icon": "Equip_liuguangjingyu",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，遭受近战攻击「对战前」，若自身气血高于80%，则物防+15%，反之物攻+15%",
        "job": "111111",
        "type": "110001",
        "lv": 1
    },
    {
        "name": "凤纹佩环",
        "icon": "Equip_fengwenpeihuan",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防+10%，遭受暴击率降低20%。",
        "job": "111111",
        "type": "010000",
        "lv": 1
    },
    {
        "name": "镶蛇银佩·烟",
        "icon": "Equip_xiangsheyinpei",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防、气血+5%，遭受近战攻击「对战中」自身物攻，法攻，暴击率+10%",
        "job": "111111",
        "type": "010001",
        "lv": 1
    },
    {
        "name": "镶蛇银佩·尘",
        "icon": "Equip_xiangsheyinpei",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防、气血+5%，遭受近战攻击「对战前」，对敌方施加「虚损II」和「失智II」状态，持续1回合。\n「虚损II」：物理免伤-20%\n「失智II」：法术免伤-20%",
        "job": "111111",
        "type": "010001",
        "lv": 1
    },
    {
        "name": "驱魔护印",
        "icon": "Equip_qumohuyin",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，遭受近战攻击「对战前」，驱散敌方1个「有益状态」。",
        "job": "111111",
        "type": "000001",
        "lv": 1
    },
    {
        "name": "炼法黑鳞",
        "icon": "Equip_lianfaheilin",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防、气血+5%，行动结束时，对自身十字方向上7格内的1名敌人施加1个随机「有害状态」，持续1回合。",
        "job": "101001",
        "type": "010001",
        "lv": 1
    },
    {
        "name": "天穹剑印",
        "icon": "Equip_tianqiongjianyin",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，行动结束时，如果本回合造成过伤害，则对自身周围3格内的1个敌人施加「乱神II」，持续1回合。\n「乱神II」：伤害-20%",
        "job": "101001",
        "type": "000001",
        "lv": 1
    },
    {
        "name": "琅環玉璧",
        "icon": "Equip_langhuanyubi",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防、气血+5%，遭受攻击「对战中」自身物防提升20%。（每回合触发1次）",
        "job": "001000",
        "type": "010001",
        "lv": 2
    },
    {
        "name": "五尊神令",
        "icon": "Equip_wuzunshenling",
        "position": "2",
        "quality": "SSR",
        "currency": "0",
        "description": "物防，气血+5%，遭受攻击「对战中」自身免伤提升20%。（间隔1回合触发）",
        "job": "100001",
        "type": "010001",
        "lv": 2
    },
    {
        "name": "无边落木·烟",
        "icon": "Equip_xianrenbihu",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+10%，气血+5%",
        "job": "111111",
        "type": "000101",
        "lv": 0
    },
    {
        "name": "无边落木·尘",
        "icon": "Equip_xianrenbihu",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+10%，物防+5%",
        "job": "111111",
        "type": "010100",
        "lv": 0
    },
    {
        "name": "月满西楼",
        "icon": "Equip_yuemanxilou",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，气血高于80%时，法防+15%",
        "job": "111111",
        "type": "000101",
        "lv": 0
    },
    {
        "name": "和光同尘",
        "icon": "Equip_buqiguyuan",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+10%，遭受远程攻击「对战后」，对自己施加「固元II」，持续1回合。\n「固元II」：法术免伤+20%",
        "job": "111111",
        "type": "000100",
        "lv": 0
    },
    {
        "name": "鲛人悲歌·烟",
        "icon": "Equip_zhulongzhixue",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，行动结束时，对自己2格范围内物攻/法攻属性最高的1个友方施加「神睿」状态，持续1回合。\n「神睿」：物攻、法攻+20%",
        "job": "010110",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "鲛人悲歌·尘",
        "icon": "Equip_zhulongzhixue",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，行动结束时，对自己2格范围内物防属性最高的1个友方施加「披甲」状态，持续1回合。\n「披甲」：物防+20%",
        "job": "010110",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "鲛人悲歌·雾",
        "icon": "Equip_zhulongzhixue",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，行动结束时，对自己2格范围内法防属性最高的1个友方施加「御魔」状态，持续1回合。\n「御魔」：法防+30%",
        "job": "010110",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "鲛人悲歌·影",
        "icon": "Equip_zhulongzhixue",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，行动结束时，对自己2格范围内会心属性最高的1个友方施加「刺骨」状态，持续1回合。\n「刺骨」：暴击率+20%",
        "job": "010110",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "行云流水·烟",
        "icon": "Equip_xingyunliushui",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，气血100%时，双防+10%",
        "job": "111111",
        "type": "000001",
        "lv": 1
    },
    {
        "name": "封血之蛊·烟",
        "icon": "Equip_fengxuezhigu",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+10%，遭受远程攻击「对战前」，对敌方造成一次「固定伤害」（法防的30%）",
        "job": "111111",
        "type": "000100",
        "lv": 1
    },
    {
        "name": "行云流水·尘",
        "icon": "Equip_xingyunliushui",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+5%，气血50%以上时法防+20%，反之物防+10%",
        "job": "111111",
        "type": "010101",
        "lv": 1
    },
    {
        "name": "封血之蛊·尘",
        "icon": "Equip_fengxuezhigu",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+10%，遭受「固定伤害」降低50%。",
        "job": "111111",
        "type": "000100",
        "lv": 1
    },
    {
        "name": "慈航普度",
        "icon": "Equip_fusangzhimu",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+5%，气血+5%，遭受远程攻击「对战前」，驱散自身1个「有害状态」。",
        "job": "111111",
        "type": "000101",
        "lv": 1
    },
    {
        "name": "万佛朝宗·烟",
        "icon": "Equip_qichongdouniu",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+5%，气血+5%，遭受远程攻击「对战前」，为自身附加1个随机「有益状态」，持续1回合。",
        "job": "010110",
        "type": "000101",
        "lv": 1
    },
    {
        "name": "万佛朝宗·尘",
        "icon": "Equip_qichongdouniu",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+5%，气血+5%，行动结束时，对自己2格范围内1个友方角色施加1个随机「有益状态」，持续1回合。",
        "job": "010110",
        "type": "000101",
        "lv": 1
    },
    {
        "name": "万佛朝宗·雾",
        "icon": "Equip_qichongdouniu",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+5%，气血+5%，行动结束时，如果本回合造成过伤害，则对自身周围3格内物攻/法攻属性最高的1个其他友方施加「极意II」，持续1回合。\n「极意II」伤害+20%",
        "job": "010110",
        "type": "000101",
        "lv": 1
    },
    {
        "name": "朝云横度",
        "icon": "Equip_piyundaiyue",
        "position": "3",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+5%，气血+5%，遭受攻击「对战中」自身免伤提升20%。（间隔1回合触发）",
        "job": "010110",
        "type": "000101",
        "lv": 2
    },
    {
        "name": "流光手镯·烟",
        "icon": "Equip_liuguangshouzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "主动攻击「对战中」，自身物攻、物防提升12%",
        "job": "111111",
        "type": "110000",
        "lv": 0
    },
    {
        "name": "流光手镯·尘",
        "icon": "Equip_liuguangshouzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "周围3格没有友方时，战斗中物攻、物防提升12%",
        "job": "111111",
        "type": "110000",
        "lv": 0
    },
    {
        "name": "妖灵饰戒·烟",
        "icon": "Equip_yaolingshijie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+8%，和「侠客」对战，所有攻防属性提升10%",
        "job": "111111",
        "type": "100000",
        "lv": 0
    },
    {
        "name": "妖灵饰戒·尘",
        "icon": "Equip_yaolingshijie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+8%，和「御风」对战，所有攻防属性提升10%",
        "job": "111111",
        "type": "100000",
        "lv": 0
    },
    {
        "name": "妖灵饰戒·雾",
        "icon": "Equip_yaolingshijie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+8%，和「铁卫」对战，所有攻防属性提升10%",
        "job": "111111",
        "type": "100000",
        "lv": 0
    },
    {
        "name": "赤霞玉戒·烟",
        "icon": "Equip_chixiayujie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，主动攻击「对战中」，法攻、法防提升12%",
        "job": "111111",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "赤霞玉戒·尘",
        "icon": "Equip_chixiayujie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，使用绝学时，法攻提升10%",
        "job": "111111",
        "type": "001001",
        "lv": 0
    },
    {
        "name": "银阑灵镯·烟",
        "icon": "Equip_yinlanlingzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+8%，和「咒师」对战，所有攻防属性提升10%",
        "job": "111111",
        "type": "001000",
        "lv": 0
    },
    {
        "name": "银阑灵镯·尘",
        "icon": "Equip_yinlanlingzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+8%，和「祝由」对战，所有攻防属性提升10%",
        "job": "111111",
        "type": "001000",
        "lv": 0
    },
    {
        "name": "银阑灵镯·雾",
        "icon": "Equip_yinlanlingzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+8%，和「羽士」对战，所有攻防属性提升10%",
        "job": "111111",
        "type": "001000",
        "lv": 0
    },
    {
        "name": "灵泉魂镯·烟",
        "icon": "Equip_lingquanhunzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "物防+8%，气血+8%",
        "job": "111111",
        "type": "010001",
        "lv": 0
    },
    {
        "name": "灵泉魂镯·尘",
        "icon": "Equip_lingquanhunzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "法防+8%，气血+8%",
        "job": "111111",
        "type": "000101",
        "lv": 0
    },
    {
        "name": "灵泉魂镯·雾",
        "icon": "Equip_lingquanhunzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "物防+8%，法防+8%",
        "job": "111111",
        "type": "010100",
        "lv": 0
    },
    {
        "name": "云龙雕环",
        "icon": "Equip_yunlongdiaohuan",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "物防、气血+5%，被近战攻击「对战中」，物防额外提升7%",
        "job": "111111",
        "type": "010001",
        "lv": 0
    },
    {
        "name": "狮首灵戒",
        "icon": "Equip_shishoulingjie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，被远程攻击「对战中」，物防、法防提升7%",
        "job": "111111",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "辉月魂戒",
        "icon": "Equip_huiyuehunjie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，使用单体治疗类绝学时，治疗效果提升30%",
        "job": "111111",
        "type": "000001",
        "lv": 0
    },
    {
        "name": "黑玉蛇戒",
        "icon": "Equip_heiyushejie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+12%，被「御风」「羽士」攻击，「对战中」自身所有攻防属性提升20%",
        "job": "111111",
        "type": "000010",
        "lv": 0
    },
    {
        "name": "凤纹灵镯·烟",
        "icon": "Equip_fengwenlingzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+12%，免疫「晕眩」「污秽」状态",
        "job": "111111",
        "type": "000010",
        "lv": 0
    },
    {
        "name": "凤纹灵镯·尘",
        "icon": "Equip_fengwenlingzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+12%，对单个目标使用绝学时，会额外驱散1个「有害状态」",
        "job": "111111",
        "type": "000010",
        "lv": 0
    },
    {
        "name": "蛇首灵戒·烟",
        "icon": "Equip_sheshoulingjie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，主动攻击「对战中」，自身物攻提升15%",
        "job": "111111",
        "type": "100001",
        "lv": 1
    },
    {
        "name": "蛇首灵戒·尘",
        "icon": "Equip_sheshoulingjie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，气血不满时，物攻提升15%。",
        "job": "111111",
        "type": "100001",
        "lv": 1
    },
    {
        "name": "蛇首灵戒·雾",
        "icon": "Equip_sheshoulingjie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，主动攻击「对战后」，对敌方造成一次「固定伤害」（物攻的15%）",
        "job": "111111",
        "type": "000001",
        "lv": 1
    },
    {
        "name": "白焰玉镯·烟",
        "icon": "Equip_baiyanyuzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+8%，主动攻击「对战中」，暴击率+20%，暴击伤害+10%",
        "job": "111111",
        "type": "100000",
        "lv": 1
    },
    {
        "name": "白焰玉镯·尘",
        "icon": "Equip_baiyanyuzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+8%，免疫「封穴」「疲弱」状态",
        "job": "111111",
        "type": "100000",
        "lv": 1
    },
    {
        "name": "玉玑灵镯·烟",
        "icon": "Equip_yujilingzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，使用单体绝学时，法攻提升15%",
        "job": "111111",
        "type": "001001",
        "lv": 1
    },
    {
        "name": "玉玑灵镯·尘",
        "icon": "Equip_yujilingzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，使用群体绝学时，法攻提升15%",
        "job": "111111",
        "type": "001001",
        "lv": 1
    },
    {
        "name": "玉玑灵镯·雾",
        "icon": "Equip_yujilingzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，气血100%时，法攻提升12%",
        "job": "111111",
        "type": "001001",
        "lv": 1
    },
    {
        "name": "玄鸩骨戒",
        "icon": "Equip_xuanzhengujie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+8%，使用绝学造成伤害时，30%的概率使该绝学冷却时间-1",
        "job": "111111",
        "type": "001000",
        "lv": 1
    },
    {
        "name": "盘龙戒",
        "icon": "Equip_panlongyujie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "法攻+8%，免疫「封咒」「疲弱」状态",
        "job": "111111",
        "type": "001000",
        "lv": 1
    },
    {
        "name": "玄龙玉戒·烟",
        "icon": "Equip_xuanlongyujie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，气血大于80%时，物防提升12%",
        "job": "111111",
        "type": "010001",
        "lv": 1
    },
    {
        "name": "玄龙玉戒·尘",
        "icon": "Equip_xuanlongyujie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+8%，气血大于80%时，法防提升12%",
        "job": "111111",
        "type": "000101",
        "lv": 1
    },
    {
        "name": "寒月玉镯",
        "icon": "Equip_hanyueyuzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "物防、法防+5%，免疫「移动力降低」「蚀御」「蚀魔」",
        "job": "111111",
        "type": "010100",
        "lv": 1
    },
    {
        "name": "寰鸟戒",
        "icon": "Equip_huanniaojie",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "气血+10%，免疫「禁疗」「固定伤害」",
        "job": "111111",
        "type": "000001",
        "lv": 1
    },
    {
        "name": "灵蛇金镯·烟",
        "icon": "Equip_lingshejinzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+12%，免疫「封咒」「禁疗」状态",
        "job": "111111",
        "type": "000010",
        "lv": 1
    },
    {
        "name": "灵蛇金镯·尘",
        "icon": "Equip_lingshejinzhuo",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+12%，行动结束时，为自身3格内的1个友方驱散1个「有害状态」",
        "job": "111111",
        "type": "000010",
        "lv": 1
    },
    {
        "name": "幻月神珠",
        "icon": "Equip_huanyueshenzhu",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "治疗效果+12%，对单个目标使用绝学时，对其施加1个随机「有益状态」",
        "job": "111111",
        "type": "000010",
        "lv": 1
    },
    {
        "name": "千稜幻玉·烟",
        "icon": "Equip_qianlenghuanyu",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "全属性+5%，主动攻击「对战后」，获得再移动（2格）（同类效果无法叠加）",
        "job": "101000",
        "type": "111101",
        "lv": 1
    },
    {
        "name": "千稜幻玉·尘",
        "icon": "Equip_qianlenghuanyu",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "全属性+5%，被攻击「对战后」，自身获得「迅捷II」状态，持续1回合。（每回合发动1次）\n「迅捷II」：移动力+2",
        "job": "111111",
        "type": "111101",
        "lv": 1
    },
    {
        "name": "幽都玉玺",
        "icon": "Equip_youdouwangxi",
        "position": "4",
        "quality": "SSR",
        "currency": "0",
        "description": "物攻+5%，移动力+1",
        "job": "101000",
        "type": "100000",
        "lv": 2
    }
]